### ISSUE TITLE
BUG when trying to grade a quiz that no-one took yet

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#27]
The following internal server error is produced in the scenario detailed in the title: 

127.0.0.1 - - [06/Mar/2022 18:27:10] "GET /quizzes-browser HTTP/1.1" 200 -
0 3 0
127.0.0.1 - - [06/Mar/2022 18:27:14] "GET /grades/4 HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tux/dev/github/EvoPIE/evopie/routes_pages.py", line 671, in quiz_grader
    q, grades, grading_details, distractors, questions, likes_given, likes_received, count_likes_received, like_scores, justification_grade = get_data(qid)
  File "/home/tux/.local/share/virtualenvs/EvoPIE-wWJma92r/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/tux/dev/github/EvoPIE/evopie/routes_pages.py", line 519, in get_data
    median, median_indices = find_median(sorted_scores)
  File "/home/tux/dev/github/EvoPIE/evopie/routes_pages.py", line 554, in find_median
    median = (sorted_list[indices[0]] + sorted_list[indices[1]]) / 2
IndexError: list index out of range

**Comment by neverdue** [comment]
Pushed a commit for this fix (b611bec1285ba8c530017b740d52da62bcdfb28b)
